export interface PvpState {
  pvpRoom: any;
  roomDetail: any;
}

export const GET_ROOM_LIST = "GET_ROOM_LIST"
export const GET_BATTLE_DATA_SUCCESS = "GET_BATTLE_DATA_SUCCESS"

export const CREATE_ROOM_SUCCESS = "CREATE_ROOM_SUCCESS"
export const ENTER_ROOM = "ENTER_ROOM";
export const ENTER_ROOM_SUCCESS = "ENTER_ROOM_SUCCESS"
export const CLOSE_ROOM_SUCCESS = "CLOSE_ROOM_SUCCESS"
export const SET_ABILITY_SUCCESS = "SET_ABILITY_SUCCESS"
export const SET_UNIT_SUCCESS = "SET_UNIT_SUCCESS"

export const CHANGE_PVP_STATUS = "CHANGE_PVP_STATUS"

export const ENEMY_CREATE_ROOM_SUCCESS = "ENEMY_CREATE_ROOM_SUCCESS"
export const ENEMY_ENTER_ROOM_SUCCESS = "ENEMY_ENTER_ROOM_SUCCESS"
export const ENEMY_SET_ABILITY_SUCCESS = "ENEMY_SET_ABILITY_SUCCESS"
export const ENEMY_SET_UNIT_SUCCESS = "ENEMY_SET_UNIT_SUCCESS"

export const ATTACK_START = "ATTACK_START";
export const ATTACK_END = "ATTACK_END";

export const SET_MY_ADDRESS = "SET_MY_ADDRESS";
export const CHANGE_TURN = "CHANGE_TURN";
export const SET_BATTLE_WINNER = "SET_BATTLE_WINNER";

export const UNIT_ATTACK_START = "UNIT_ATTACK_START";
export const UNIT_ATTACK_END = "UNIT_ATTACK_END";

export const SET_READY_ALL_PLAYERS = "SET_READY_ALL_PLAYERS";

export const UPDATE_BONUS_DAMAGE = "UPDATE_BONUS_DAMAGE";

export const CHANGE_PVP_ROOM_STATUS = "CHANGE_PVP_ROOM_STATUS";

export const SCENE_READY = "SCENE_READY";

export const ERROR = "ERROR";