export const PVP_STATUS = {
    SELECT_ROOM: "SELECT_ROOM",
    SELECT_UNIT: "SELECT_UNIT",
    SELECT_SPELL: "SELELCT_SPELL",
    WAITING: "WAITING",
    PLAY: "PLAY",
    END: "END",
}

export const PVP_ATTACK_TURN = {
    LOCAL_PLAYER: "LOCAL_PLAYER",
    REMOTE_PLAYER: "REMOTE_PLAYER",
}

export const DEFAULT_HP = 1000;